import './globals.css';
import { CocktailProvider } from './context/CocktailContext';
import './globals.css';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				{/* Enveloppez l'application avec le fournisseur de contexte */}
				<CocktailProvider>{children}</CocktailProvider>
			</body>
		</html>
	);
}
